version: '3'

networks:
  testing:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    networks:
      testing:
        ipv4_address: 172.21.0.2
    restart: unless-stopped

  db:
    image: mysql:9.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    networks:
      testing:
        ipv4_address: 172.21.0.3
