FROM node:16 AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:16

COPY package*.json .

RUN npm ci --omit=dev && rm package-lock.json node_modules/.package-lock.json

COPY --from=build /app/dist ./
COPY --from=build /app/prisma ./

RUN npx prisma generate

CMD ["node", "./src/app.js"]
